// <auto-generated />
using System;
using Marketplace.Api.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Marketplace.Api.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260811191744_PerfilProfesional")]
    partial class PerfilProfesional
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Marketplace.Api.Core.Models.CuentaCorriente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<decimal>("Monto")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("monto");

                    b.Property<int>("ProfesionalId")
                        .HasColumnType("integer")
                        .HasColumnName("profesional_id");

                    b.Property<string>("Referencia")
                        .HasColumnType("text")
                        .HasColumnName("referencia");

                    b.Property<decimal>("SaldoPosterior")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("saldo_posterior");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("tipo");

                    b.Property<int?>("TrabajoId")
                        .HasColumnType("integer")
                        .HasColumnName("trabajo_id");

                    b.HasKey("Id")
                        .HasName("pk_cuenta_corriente");

                    b.HasIndex("TrabajoId")
                        .HasDatabaseName("ix_cuenta_corriente_trabajo_id");

                    b.HasIndex("ProfesionalId", "CreadoEn")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_cuenta_corriente_profesional_id_creado_en");

                    b.ToTable("CuentaCorriente", null, t =>
                        {
                            t.HasCheckConstraint("CK_CC_tipo", "tipo IN ('comision_adeudada', 'pago_deuda', 'ajuste_manual')");
                        });
                });

            modelBuilder.Entity("Marketplace.Api.Core.Models.Pago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Comision")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("comision");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<decimal>("MontoTotal")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("monto_total");

                    b.Property<string>("TipoPago")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo_pago");

                    b.Property<int>("TrabajoId")
                        .HasColumnType("integer")
                        .HasColumnName("trabajo_id");

                    b.HasKey("Id")
                        .HasName("pk_pagos");

                    b.HasIndex("TrabajoId")
                        .IsUnique()
                        .HasDatabaseName("ix_pagos_trabajo_id");

                    b.ToTable("Pagos", null, t =>
                        {
                            t.HasCheckConstraint("CK_Pagos_estado", "estado IN ('registrado', 'conciliado', 'reembolsado')");

                            t.HasCheckConstraint("CK_Pagos_tipo_pago", "tipo_pago IN ('efectivo', 'tarjeta', 'transferencia')");
                        });
                });

            modelBuilder.Entity("Marketplace.Api.Core.Models.Postulacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<decimal?>("Presupuesto")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("presupuesto");

                    b.Property<int>("ProfesionalId")
                        .HasColumnType("integer")
                        .HasColumnName("profesional_id");

                    b.Property<int>("TrabajoId")
                        .HasColumnType("integer")
                        .HasColumnName("trabajo_id");

                    b.HasKey("Id")
                        .HasName("pk_postulaciones");

                    b.HasIndex("ProfesionalId")
                        .HasDatabaseName("ix_postulaciones_profesional_id");

                    b.HasIndex("TrabajoId", "ProfesionalId")
                        .IsUnique()
                        .HasDatabaseName("ix_postulaciones_trabajo_id_profesional_id");

                    b.ToTable("Postulaciones", (string)null);
                });

            modelBuilder.Entity("Marketplace.Api.Core.Models.ProfesionalServicio", b =>
                {
                    b.Property<int>("ProfesionalId")
                        .HasColumnType("integer")
                        .HasColumnName("profesional_id");

                    b.Property<int>("ServicioId")
                        .HasColumnType("integer")
                        .HasColumnName("servicio_id");

                    b.HasKey("ProfesionalId", "ServicioId")
                        .HasName("pk_profesional_servicios");

                    b.HasIndex("ServicioId")
                        .HasDatabaseName("ix_profesional_servicios_servicio_id");

                    b.ToTable("ProfesionalServicios", (string)null);
                });

            modelBuilder.Entity("Marketplace.Api.Core.Models.Resenia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer")
                        .HasColumnName("cliente_id");

                    b.Property<string>("Comentario")
                        .HasColumnType("text")
                        .HasColumnName("comentario");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<int>("ProfesionalId")
                        .HasColumnType("integer")
                        .HasColumnName("profesional_id");

                    b.Property<byte>("Puntuacion")
                        .HasColumnType("smallint")
                        .HasColumnName("puntuacion");

                    b.Property<int>("TrabajoId")
                        .HasColumnType("integer")
                        .HasColumnName("trabajo_id");

                    b.HasKey("Id")
                        .HasName("pk_resenias");

                    b.HasIndex("ClienteId")
                        .HasDatabaseName("ix_resenias_cliente_id");

                    b.HasIndex("TrabajoId")
                        .IsUnique()
                        .HasDatabaseName("ix_resenias_trabajo_id");

                    b.HasIndex("ProfesionalId", "Puntuacion")
                        .HasDatabaseName("ix_resenias_profesional_id_puntuacion");

                    b.ToTable("Resenias", null, t =>
                        {
                            t.HasCheckConstraint("CK_Resenias_puntuacion", "puntuacion BETWEEN 1 AND 5");
                        });
                });

            modelBuilder.Entity("Marketplace.Api.Core.Models.Servicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("pk_servicios");

                    b.ToTable("Servicios", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreadoEn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descripcion = "Instalacion, reparacion y mantenimiento de artefactos a gas",
                            Nombre = "Gasista"
                        },
                        new
                        {
                            Id = 2,
                            CreadoEn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descripcion = "Instalaciones electricas, reparaciones y certificaciones",
                            Nombre = "Electricista"
                        },
                        new
                        {
                            Id = 3,
                            CreadoEn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descripcion = "Reparacion de canerias, termotanques y sanitarios",
                            Nombre = "Plomero"
                        },
                        new
                        {
                            Id = 4,
                            CreadoEn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descripcion = "Pintura interior y exterior, enduido y revestimientos",
                            Nombre = "Pintor"
                        },
                        new
                        {
                            Id = 5,
                            CreadoEn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descripcion = "Apertura de puertas, cambio de cerraduras y copias",
                            Nombre = "Cerrajero"
                        },
                        new
                        {
                            Id = 6,
                            CreadoEn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descripcion = "Muebles a medida, reparacion de aberturas y colocacion",
                            Nombre = "Carpintero"
                        },
                        new
                        {
                            Id = 7,
                            CreadoEn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descripcion = "Arreglos de paredes, contrapisos y revoques",
                            Nombre = "Albanil"
                        },
                        new
                        {
                            Id = 8,
                            CreadoEn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descripcion = "Reparacion de techos, filtraciones y membranas",
                            Nombre = "Techista"
                        },
                        new
                        {
                            Id = 9,
                            CreadoEn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descripcion = "Corte de cesped, poda, diseno de jardines",
                            Nombre = "Jardinero"
                        },
                        new
                        {
                            Id = 10,
                            CreadoEn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descripcion = "Reparacion de electrodomesticos y equipos electronicos",
                            Nombre = "Servicio Tecnico"
                        });
                });

            modelBuilder.Entity("Marketplace.Api.Core.Models.Trabajo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en");

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer")
                        .HasColumnName("cliente_id");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<string>("DireccionDestino")
                        .HasColumnType("text")
                        .HasColumnName("direccion_destino");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<decimal?>("LatitudDestino")
                        .HasPrecision(10, 7)
                        .HasColumnType("numeric(10,7)")
                        .HasColumnName("latitud_destino");

                    b.Property<decimal?>("LatitudInicio")
                        .HasPrecision(10, 7)
                        .HasColumnType("numeric(10,7)")
                        .HasColumnName("latitud_inicio");

                    b.Property<decimal?>("LongitudDestino")
                        .HasPrecision(10, 7)
                        .HasColumnType("numeric(10,7)")
                        .HasColumnName("longitud_destino");

                    b.Property<decimal?>("LongitudInicio")
                        .HasPrecision(10, 7)
                        .HasColumnType("numeric(10,7)")
                        .HasColumnName("longitud_inicio");

                    b.Property<int?>("ProfesionalId")
                        .HasColumnType("integer")
                        .HasColumnName("profesional_id");

                    b.Property<int>("ServicioId")
                        .HasColumnType("integer")
                        .HasColumnName("servicio_id");

                    b.Property<string>("TipoPago")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo_pago");

                    b.HasKey("Id")
                        .HasName("pk_trabajos");

                    b.HasIndex("ServicioId")
                        .HasDatabaseName("ix_trabajos_servicio_id");

                    b.HasIndex("ClienteId", "Estado")
                        .HasDatabaseName("ix_trabajos_cliente_id_estado");

                    b.HasIndex("ProfesionalId", "Estado")
                        .HasDatabaseName("ix_trabajos_profesional_id_estado");

                    b.HasIndex("Estado", "LatitudDestino", "LongitudDestino")
                        .HasDatabaseName("ix_trabajos_estado_latitud_destino_longitud_destino")
                        .HasFilter("estado IN ('pendiente', 'aceptado')");

                    b.ToTable("Trabajos", null, t =>
                        {
                            t.HasCheckConstraint("CK_Trabajos_estado", "estado IN ('pendiente', 'aceptado', 'viajando', 'en_progreso', 'completado', 'cancelado')");

                            t.HasCheckConstraint("CK_Trabajos_tipo_pago", "tipo_pago IN ('efectivo', 'tarjeta', 'transferencia')");
                        });
                });

            modelBuilder.Entity("Marketplace.Api.Core.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<string>("Cuit")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cuit");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("descripcion");

                    b.Property<bool>("Disponible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("disponible");

                    b.Property<string>("Dni")
                        .HasColumnType("text")
                        .HasColumnName("dni");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<int>("Estado")
                        .HasColumnType("integer")
                        .HasColumnName("estado");

                    b.Property<string>("NivelProfesional")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("nivel_profesional");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<string>("NumeroMatricula")
                        .HasColumnType("text")
                        .HasColumnName("numero_matricula");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<int?>("RadioCoberturaKm")
                        .HasColumnType("integer")
                        .HasColumnName("radio_cobertura_km");

                    b.Property<string>("RazonSocial")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("razon_social");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("rol");

                    b.Property<string>("Telefono")
                        .HasColumnType("text")
                        .HasColumnName("telefono");

                    b.Property<string>("TipoPerfil")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("persona")
                        .HasColumnName("tipo_perfil");

                    b.Property<Point>("Ubicacion")
                        .HasColumnType("geography (point,4326)")
                        .HasColumnName("ubicacion");

                    b.HasKey("Id")
                        .HasName("pk_usuarios");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_usuarios_email");

                    b.HasIndex("Ubicacion")
                        .HasDatabaseName("ix_usuarios_ubicacion");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Ubicacion"), "gist");

                    b.ToTable("Usuarios", null, t =>
                        {
                            t.HasCheckConstraint("CK_Usuarios_dni", "(rol = 'profesional' AND dni IS NOT NULL) OR (rol IN ('cliente', 'admin'))");

                            t.HasCheckConstraint("CK_Usuarios_empresa", "(tipo_perfil = 'persona' AND razon_social IS NULL AND cuit IS NULL) OR (tipo_perfil = 'empresa' AND razon_social IS NOT NULL)");

                            t.HasCheckConstraint("CK_Usuarios_matricula", "(rol = 'cliente' AND numero_matricula IS NULL) OR (rol = 'profesional' AND nivel_profesional = 'standard' AND numero_matricula IS NULL) OR (rol = 'profesional' AND nivel_profesional = 'premium' AND numero_matricula IS NOT NULL) OR (rol = 'admin' AND numero_matricula IS NULL)");

                            t.HasCheckConstraint("CK_Usuarios_nivel", "(rol = 'cliente' AND nivel_profesional IS NULL) OR (rol = 'profesional' AND nivel_profesional IN ('standard', 'premium')) OR (rol = 'admin' AND nivel_profesional IS NULL)");

                            t.HasCheckConstraint("CK_Usuarios_radio", "radio_cobertura_km IS NULL OR radio_cobertura_km BETWEEN 1 AND 200");

                            t.HasCheckConstraint("CK_Usuarios_rol", "rol IN ('cliente', 'profesional', 'admin')");

                            t.HasCheckConstraint("CK_Usuarios_tipo_perfil", "tipo_perfil IN ('persona', 'empresa')");
                        });
                });

            modelBuilder.Entity("Marketplace.Api.Core.Models.CuentaCorriente", b =>
                {
                    b.HasOne("Marketplace.Api.Core.Models.Usuario", "Profesional")
                        .WithMany("CuentaCorriente")
                        .HasForeignKey("ProfesionalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cuenta_corriente_usuarios_profesional_id");

                    b.HasOne("Marketplace.Api.Core.Models.Trabajo", "Trabajo")
                        .WithMany("CuentaCorriente")
                        .HasForeignKey("TrabajoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_cuenta_corriente_trabajos_trabajo_id");

                    b.Navigation("Profesional");

                    b.Navigation("Trabajo");
                });

            modelBuilder.Entity("Marketplace.Api.Core.Models.Pago", b =>
                {
                    b.HasOne("Marketplace.Api.Core.Models.Trabajo", "Trabajo")
                        .WithOne("Pago")
                        .HasForeignKey("Marketplace.Api.Core.Models.Pago", "TrabajoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pagos_trabajos_trabajo_id");

                    b.Navigation("Trabajo");
                });

            modelBuilder.Entity("Marketplace.Api.Core.Models.Postulacion", b =>
                {
                    b.HasOne("Marketplace.Api.Core.Models.Usuario", "Profesional")
                        .WithMany()
                        .HasForeignKey("ProfesionalId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_postulaciones_usuarios_profesional_id");

                    b.HasOne("Marketplace.Api.Core.Models.Trabajo", "Trabajo")
                        .WithMany("Postulaciones")
                        .HasForeignKey("TrabajoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_postulaciones_trabajos_trabajo_id");

                    b.Navigation("Profesional");

                    b.Navigation("Trabajo");
                });

            modelBuilder.Entity("Marketplace.Api.Core.Models.ProfesionalServicio", b =>
                {
                    b.HasOne("Marketplace.Api.Core.Models.Usuario", "Profesional")
                        .WithMany("Servicios")
                        .HasForeignKey("ProfesionalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_profesional_servicios_usuarios_profesional_id");

                    b.HasOne("Marketplace.Api.Core.Models.Servicio", "Servicio")
                        .WithMany("Profesionales")
                        .HasForeignKey("ServicioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_profesional_servicios_servicios_servicio_id");

                    b.Navigation("Profesional");

                    b.Navigation("Servicio");
                });

            modelBuilder.Entity("Marketplace.Api.Core.Models.Resenia", b =>
                {
                    b.HasOne("Marketplace.Api.Core.Models.Usuario", "Cliente")
                        .WithMany("ReseniasEscritas")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_resenias_usuarios_cliente_id");

                    b.HasOne("Marketplace.Api.Core.Models.Usuario", "Profesional")
                        .WithMany("ReseniasRecibidas")
                        .HasForeignKey("ProfesionalId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_resenias_usuarios_profesional_id");

                    b.HasOne("Marketplace.Api.Core.Models.Trabajo", "Trabajo")
                        .WithOne("Resenia")
                        .HasForeignKey("Marketplace.Api.Core.Models.Resenia", "TrabajoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_resenias_trabajos_trabajo_id");

                    b.Navigation("Cliente");

                    b.Navigation("Profesional");

                    b.Navigation("Trabajo");
                });

            modelBuilder.Entity("Marketplace.Api.Core.Models.Trabajo", b =>
                {
                    b.HasOne("Marketplace.Api.Core.Models.Usuario", "Cliente")
                        .WithMany("TrabajosComoCliente")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_trabajos_usuarios_cliente_id");

                    b.HasOne("Marketplace.Api.Core.Models.Usuario", "Profesional")
                        .WithMany("TrabajosComoProfesional")
                        .HasForeignKey("ProfesionalId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_trabajos_usuarios_profesional_id");

                    b.HasOne("Marketplace.Api.Core.Models.Servicio", "Servicio")
                        .WithMany()
                        .HasForeignKey("ServicioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_trabajos_servicios_servicio_id");

                    b.Navigation("Cliente");

                    b.Navigation("Profesional");

                    b.Navigation("Servicio");
                });

            modelBuilder.Entity("Marketplace.Api.Core.Models.Servicio", b =>
                {
                    b.Navigation("Profesionales");
                });

            modelBuilder.Entity("Marketplace.Api.Core.Models.Trabajo", b =>
                {
                    b.Navigation("CuentaCorriente");

                    b.Navigation("Pago");

                    b.Navigation("Postulaciones");

                    b.Navigation("Resenia");
                });

            modelBuilder.Entity("Marketplace.Api.Core.Models.Usuario", b =>
                {
                    b.Navigation("CuentaCorriente");

                    b.Navigation("ReseniasEscritas");

                    b.Navigation("ReseniasRecibidas");

                    b.Navigation("Servicios");

                    b.Navigation("TrabajosComoCliente");

                    b.Navigation("TrabajosComoProfesional");
                });
#pragma warning restore 612, 618
        }
    }
}
